### PR TITLE
create development branch as required by TS's

### PR DESCRIPTION
**Pull request by Joecleverman**
Create enum methods such as: #each, #each_with_index, #select, #all?, #any?, #none?, #count, #map, #inject re-written in custom algorithm.
create with different files for testing - enumerable_test.rb and enumerable_methods.rb.
.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @Joecleverman and @techbabouche :clap: :clap:
#### Excellent job :+1: but you still need to make some changes before this project can be approved.

**_1. Add the name of the second author to the readme file._**

**_2. Change `odd` to `odd?` on line 19 of the enumerable_test file._**

**_3. Fix multiply_els(element) on line 91 of the enumerable_test file, it's not working._**

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by Joecleverman** [comment]
1) For the first correction, I'm both Joecleverman and Techbabouche I have two Github account but for some reason, they have been merge and I do everything I can but until now I'm not able to get rid of that.
2) Secondly I change odd to odd?
3) I solve the multiply_els issue

Thanks for reviewing it again.

**Comment by uryelah** [comment]
Hello **Joe Abraham**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

---------    
    
Good job fixing the last required changes.

On an OPTIONAL note, I'd advice you to take some time to refactor your code instead of disabling rubocop for module/method length and complexity. Those issues can easily be solved by refactoring some code out, you could make a helper methods module to put them on, or trying to simplify it.  
By doing that you, hopefully, will get a code that's more modular and easier to test and debug in the future.

---------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
